spring.application.name=demo

# Aiven MySQL 연결
spring.datasource.url=jdbc:mysql://mysql-131a9df2-my-todo.e.aivencloud.com:23797/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 테이블 자동 생성 및 관리
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true